---
- name: Install general (non-X11) tools
  apt:
    pkg:
      - 7zip
      - bc
      - bind9-utils
      - bsdgames
      - calibre
      - cmake
      - cpuid
      - cryptsetup-bin
      - curl
      - dc
      - ddate
      - dict
      - debootstrap
      - diffstat
      - dmidecode
      - enscript
      - ethtool
      - ffmpeg
      - gawk
      - git
      - git-lfs
      - gnuplot
      - htop
      - imagemagick
      - intel-microcode
      - iperf3
      - ipmitool
      - jc
      - jnettop
      - jq
      - kbd
      - lbzip2
      - lftp
      - libimage-exiftool-perl
      - libkf5wallet-bin
      - libtorrent21t64
      - lm-sensors
      - lshw
      - lsof
      - lsscsi
      - ltrace
      - lvm2
      - m4
      - mbw
      - mcrypt
      - mdadm
      - mediainfo
      - mt-st
      - ncal
      - netperf
      - net-tools
      - nfs-common
      - nmap
      - nodejs
      - npm
      - nvme-cli
      - oathtool
      - openssh-client
      - openvpn
      - p7zip-full
      - parted
      - pcm
      - pdftk
      - pipx
      - prometheus-node-exporter
      - psutils
      - python3-poetry
      - rclone
      - ripgrep
      - rpm2cpio
      - rsync
      - sshpass
      - smartmontools
      - snmp
      - stenc
      - strace
      - sysstat
      - sysv-rc-conf
      - telnet
      - tmux
      - traceroute
      - units
      - unrar
      - unzip
      - usbutils
      - vim
      - vmdb2
      - vnstat
      - whois
      - wtmpdb
      - xz-utils
      - zarchive-tools
      - zbar-tools
      - zerofree
      - zip
      - zsh
