---
- name: Install virtualization tools
  apt:
    pkg:
      - libvirt-clients
      - libvirt-daemon
      - libvirt-daemon-system
      - samba
      - virtiofsd
      - virt-manager
      - virt-top
      - virt-viewer
      - vmdb2
